services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    networks:
      - mosquitto
    ports:
      - "1883:1883/tcp"
    volumes:
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - ./config:/mosquitto/config

networks:
  mosquitto:
    name: mosquitto
