http:
  routers:
    hass:
      rule: "Host(`hass.lan`)"
      entryPoints:
        - web
      service: hass
  services:
    hass:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8123"
